// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// gaussian
double gaussian(double mean, double stdev, double x);
RcppExport SEXP _RNAmrf_gaussian(SEXP meanSEXP, SEXP stdevSEXP, SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type mean(meanSEXP);
    Rcpp::traits::input_parameter< double >::type stdev(stdevSEXP);
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussian(mean, stdev, x));
    return rcpp_result_gen;
END_RCPP
}
// test
NumericVector test(NumericVector x);
RcppExport SEXP _RNAmrf_test(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(test(x));
    return rcpp_result_gen;
END_RCPP
}
// Falign
double Falign(NumericMatrix sco_mtx);
RcppExport SEXP _RNAmrf_Falign(SEXP sco_mtxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sco_mtx(sco_mtxSEXP);
    rcpp_result_gen = Rcpp::wrap(Falign(sco_mtx));
    return rcpp_result_gen;
END_RCPP
}
// retrieve_matj
double retrieve_matj(int i, int a, int j, int b, NumericMatrix mat_j, int len_a);
RcppExport SEXP _RNAmrf_retrieve_matj(SEXP iSEXP, SEXP aSEXP, SEXP jSEXP, SEXP bSEXP, SEXP mat_jSEXP, SEXP len_aSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type a(aSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type b(bSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat_j(mat_jSEXP);
    Rcpp::traits::input_parameter< int >::type len_a(len_aSEXP);
    rcpp_result_gen = Rcpp::wrap(retrieve_matj(i, a, j, b, mat_j, len_a));
    return rcpp_result_gen;
END_RCPP
}
// ini_SCO
NumericMatrix ini_SCO(IntegerVector seq, NumericMatrix mrf_mat, NumericMatrix mrf_h, int mrf_len, double sep_x, double sep_y);
RcppExport SEXP _RNAmrf_ini_SCO(SEXP seqSEXP, SEXP mrf_matSEXP, SEXP mrf_hSEXP, SEXP mrf_lenSEXP, SEXP sep_xSEXP, SEXP sep_ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mrf_mat(mrf_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mrf_h(mrf_hSEXP);
    Rcpp::traits::input_parameter< int >::type mrf_len(mrf_lenSEXP);
    Rcpp::traits::input_parameter< double >::type sep_x(sep_xSEXP);
    Rcpp::traits::input_parameter< double >::type sep_y(sep_ySEXP);
    rcpp_result_gen = Rcpp::wrap(ini_SCO(seq, mrf_mat, mrf_h, mrf_len, sep_x, sep_y));
    return rcpp_result_gen;
END_RCPP
}
// ini_SCO_simple
NumericMatrix ini_SCO_simple(IntegerVector seq, NumericMatrix mrf_h);
RcppExport SEXP _RNAmrf_ini_SCO_simple(SEXP seqSEXP, SEXP mrf_hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mrf_h(mrf_hSEXP);
    rcpp_result_gen = Rcpp::wrap(ini_SCO_simple(seq, mrf_h));
    return rcpp_result_gen;
END_RCPP
}
// align
IntegerVector align(NumericMatrix sco_mtx, double gap_ext, double gap_open);
RcppExport SEXP _RNAmrf_align(SEXP sco_mtxSEXP, SEXP gap_extSEXP, SEXP gap_openSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type sco_mtx(sco_mtxSEXP);
    Rcpp::traits::input_parameter< double >::type gap_ext(gap_extSEXP);
    Rcpp::traits::input_parameter< double >::type gap_open(gap_openSEXP);
    rcpp_result_gen = Rcpp::wrap(align(sco_mtx, gap_ext, gap_open));
    return rcpp_result_gen;
END_RCPP
}
// score_aln
DoubleVector score_aln(IntegerVector a2b, IntegerVector seq, NumericMatrix mrf_mat, NumericMatrix mrf_h, bool DEBUG);
RcppExport SEXP _RNAmrf_score_aln(SEXP a2bSEXP, SEXP seqSEXP, SEXP mrf_matSEXP, SEXP mrf_hSEXP, SEXP DEBUGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type a2b(a2bSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mrf_mat(mrf_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mrf_h(mrf_hSEXP);
    Rcpp::traits::input_parameter< bool >::type DEBUG(DEBUGSEXP);
    rcpp_result_gen = Rcpp::wrap(score_aln(a2b, seq, mrf_mat, mrf_h, DEBUG));
    return rcpp_result_gen;
END_RCPP
}
// mod_SCO
NumericMatrix mod_SCO(NumericMatrix SCO, int iteration, IntegerVector seq, NumericMatrix mrf_mat, NumericMatrix mrf_h, double wt_h, double wt_j, double gap_o, double gap_e, bool DEBUG);
RcppExport SEXP _RNAmrf_mod_SCO(SEXP SCOSEXP, SEXP iterationSEXP, SEXP seqSEXP, SEXP mrf_matSEXP, SEXP mrf_hSEXP, SEXP wt_hSEXP, SEXP wt_jSEXP, SEXP gap_oSEXP, SEXP gap_eSEXP, SEXP DEBUGSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type SCO(SCOSEXP);
    Rcpp::traits::input_parameter< int >::type iteration(iterationSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type seq(seqSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mrf_mat(mrf_matSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mrf_h(mrf_hSEXP);
    Rcpp::traits::input_parameter< double >::type wt_h(wt_hSEXP);
    Rcpp::traits::input_parameter< double >::type wt_j(wt_jSEXP);
    Rcpp::traits::input_parameter< double >::type gap_o(gap_oSEXP);
    Rcpp::traits::input_parameter< double >::type gap_e(gap_eSEXP);
    Rcpp::traits::input_parameter< bool >::type DEBUG(DEBUGSEXP);
    rcpp_result_gen = Rcpp::wrap(mod_SCO(SCO, iteration, seq, mrf_mat, mrf_h, wt_h, wt_j, gap_o, gap_e, DEBUG));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello
List rcpp_hello();
RcppExport SEXP _RNAmrf_rcpp_hello() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RNAmrf_gaussian", (DL_FUNC) &_RNAmrf_gaussian, 3},
    {"_RNAmrf_test", (DL_FUNC) &_RNAmrf_test, 1},
    {"_RNAmrf_Falign", (DL_FUNC) &_RNAmrf_Falign, 1},
    {"_RNAmrf_retrieve_matj", (DL_FUNC) &_RNAmrf_retrieve_matj, 6},
    {"_RNAmrf_ini_SCO", (DL_FUNC) &_RNAmrf_ini_SCO, 6},
    {"_RNAmrf_ini_SCO_simple", (DL_FUNC) &_RNAmrf_ini_SCO_simple, 2},
    {"_RNAmrf_align", (DL_FUNC) &_RNAmrf_align, 3},
    {"_RNAmrf_score_aln", (DL_FUNC) &_RNAmrf_score_aln, 5},
    {"_RNAmrf_mod_SCO", (DL_FUNC) &_RNAmrf_mod_SCO, 10},
    {"_RNAmrf_rcpp_hello", (DL_FUNC) &_RNAmrf_rcpp_hello, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_RNAmrf(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
